# Site settings
title: "Software Enginneer Resume"
description: "The Software Engineer job resume of Frank Ittermann."

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/126682769?v=4

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Build settings
markdown: kramdown

kramdown:
   parse_block_html: true
   html_to_native: true
   toc_levels: 2..3

sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Frank Ittermann"
resume_title:                   "Senior Platform Engineer / Senior Site Reliability Engineer / Senior Backend Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "frank.ittermann@yahoo.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "15+ years of software and system engineering experience."
display_header_contact_info:    "true"

resume_header_intro: "<p>Everything seems to be impossible until it is accomplished.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_principles:      true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/fr12k"
  resume_github_url2:           "https://github.com/fr123k"

  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/frank-ittermann"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_goodreads_url:          "https://www.goodreads.com/user/show/117403451-frank"
  resume_website_url:           "https://profile.fr123k.uk"
  #resume_medium_url:             ""
resume_print_social_links:      true

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

google_analytics: G-M265JH5QM2
